spring:
  datasource:
    url: 'jdbc:h2:mem:tasks'
    driver-class-name: 'org.h2.Driver'
    username: 'sa'
    password: 'password'
    data: 'classpath*:database/data.sql'
    schema: 'classpath*:database/schema.sql'
  jpa:
    hibernate:
      ddl-auto: none
  profiles:
    active: 'dev'
  h2:
    console:
      enabled: true
      path: '/h2-console'