spring:
  datasource:
    url: 'jdbc:h2:mem:task_management'
    driver-class-name: 'org.h2.Driver'
    username: 'sa'
    password: 'password'
    data: 'classpath*:database/data.sql'
    schema: 'classpath*:database/schema_h2.sql'
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate: DEBUG
    com.study: TRACE
jwt:
  header: Authorization
  secret: secretKey
  expiration: 3600
