spring:
  datasource:
    url: 'jdbc:h2:mem:tasks'
    driver-class-name: 'org.h2.Driver'
    username: 'sa'
    password: 'password'
    data: 'classpath*:database/data.sql'
    schema: 'classpath*:database/schema.sql'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  profiles:
    active: 'dev'
  h2:
    console:
      enabled: true
      path: '/h2-console'
logging:
  level:
    root: ERROR
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.study: TRACE